# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c6cd54d11050c82d7bfc32821d2bd1b7cb2651dcc056687237ac06ccc4a6434cd989edbec0f984b5b3448231a4b8348bdfa18a2adbae2cf437f17b05c29cc6e

test:
  secret_key_base: 9a39603f429c7258b86c858432917d11f7603b34533ec8d82f52d7923964f8f26f7b9705b922962a033700d46a4f71f61a25eda0b7e3c236fb3a06e3e2fd303d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
